android.support.v4.c.s extends java.util.concurrent.FutureTask
final android.support.v4.c.p a
    void <init>(android.support.v4.c.p, java.util.concurrent.Callable)
    {
        android.support.v4.c.s r0;
        android.support.v4.c.p $r1;
        java.util.concurrent.Callable $r2;

        r0 := @this: android.support.v4.c.s;

        $r1 := @parameter0: android.support.v4.c.p;

        $r2 := @parameter1: java.util.concurrent.Callable;

        r0.<android.support.v4.c.s: android.support.v4.c.p a> = $r1;

        specialinvoke r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);

        return;
    }
    protected void done()
    {
        android.support.v4.c.s r0;
        java.lang.Object $r1;
        android.support.v4.c.p $r2;
        java.lang.InterruptedException $r3;
        java.util.concurrent.ExecutionException $r4;
        java.lang.RuntimeException $r5;
        java.lang.Throwable $r6;
        java.util.concurrent.CancellationException $r7;

        r0 := @this: android.support.v4.c.s;

     label1:
        $r1 = virtualinvoke r0.<android.support.v4.c.s: java.lang.Object get()>();

     label2:
        $r2 = r0.<android.support.v4.c.s: android.support.v4.c.p a>;

     label3:
        staticinvoke <android.support.v4.c.p: void b(android.support.v4.c.p,java.lang.Object)>($r2, $r1);

     label4:
        return;

     label5:
        $r3 := @caughtexception;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r3);

        return;

     label6:
        $r4 := @caughtexception;

        $r5 = new java.lang.RuntimeException;

        $r6 = virtualinvoke $r4.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occurred while executing doInBackground()", $r6);

        throw $r5;

     label7:
        $r7 := @caughtexception;

        $r2 = r0.<android.support.v4.c.s: android.support.v4.c.p a>;

        staticinvoke <android.support.v4.c.p: void b(android.support.v4.c.p,java.lang.Object)>($r2, null);

        return;

     label8:
        $r6 := @caughtexception;

        $r5 = new java.lang.RuntimeException;

        specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occurred while executing doInBackground()", $r6);

        throw $r5;

        catch java.lang.InterruptedException from label1 to label2 with label5;
        catch java.lang.InterruptedException from label3 to label4 with label5;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label6;
        catch java.util.concurrent.ExecutionException from label3 to label4 with label6;
        catch java.util.concurrent.CancellationException from label1 to label2 with label7;
        catch java.util.concurrent.CancellationException from label3 to label4 with label7;
        catch java.lang.Throwable from label1 to label4 with label8;
    }
